### ISSUE TITLE
Fail to decode https response

### ISSUE THREAD

**Issue by loicknuchel** [criteo/lolhttp#19]
Using `lolhttp 0.4.0` and trying to reach `https://jsonplaceholder.typicode.com/users` leads to SSL error :
```
mai 23, 2017 1:08:57 PM lol.http.internal.io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
AVERTISSEMENT: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
lol.http.internal.io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at lol.http.internal.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	...
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	...

The future returned an exception of type: lol.http.Error, with message: Connection closed.
ScalaTestFailureLocation: org.sample.HelloLol at (HelloLol.scala:26)
org.scalatest.exceptions.TestFailedException: The future returned an exception of type: lol.http.Error, with message: Connection closed.
	at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
	...
Caused by: lol.http.Error: Connection closed
	at lol.http.Error$.<init>(Errors.scala:30)
	...
```

Here is the code :
```scala
class HelloLol extends FunSpec with Matchers with ScalaFutures with BeforeAndAfterAll {
  implicit val defaultPatience = PatienceConfig(timeout = Span(5, Seconds), interval = Span(500, Millis))
  val typicodeClient = Client("jsonplaceholder.typicode.com", 443, "https", ssl = SSL.trustAll)

  override def afterAll(): Unit = {
    typicodeClient.stop()
  }

  describe("LOL") {
    it("should perform requests") {
      val res = typicodeClient.run(Get("/users")) { response =>
        response.readAs[Json].map(root.each.username.string.getAll)
      }
      res.futureValue shouldBe List()
    }
  }
}
```

**Comment by guillaumebort** [comment]
The certificate used by this website is not recognised by the default TrustStore of the JVM.
